services:
   flooded-area-moderation-discord:
      build:
         context: .
         dockerfile: ./flooded-area-moderation-discord/Dockerfile
      container_name: flooded-area-moderation-discord
      deploy:
         restart_policy:
            condition: on-failure
            delay: 2m
            max_attempts: 3
      develop:
         watch:
            - path: ./flooded-area-moderation-discord/
              action: rebuild
            - path: ./package-lock.json
              action: rebuild
      environment:
         TZ: Europe/London
      labels:
         com.fennec.app_type: discord
         com.fennec.app_name: flooded-area-moderation